# ruff: noqa
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
from zoneinfo import ZoneInfo

from google.adk.agents import Agent
from google.adk.apps import App
from google.adk.models import Gemini
from google.genai import types

import os
import google.auth

try:
    _, project_id = google.auth.default()
    os.environ["GOOGLE_CLOUD_PROJECT"] = project_id
except Exception:
    os.environ["GOOGLE_CLOUD_PROJECT"] = os.getenv("GOOGLE_CLOUD_PROJECT", "dummy-project")
os.environ["GOOGLE_CLOUD_LOCATION"] = "global"
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"


def get_weather(query: str) -> str:
    """Simulates a web search. Use it get information on weather.

    Args:
        query: A string containing the location to get weather information for.

    Returns:
        A string with the simulated weather information for the queried location.
    """
    if "sf" in query.lower() or "san francisco" in query.lower():
        return "It's 60 degrees and foggy."
    return "It's 90 degrees and sunny."


def get_current_time(query: str) -> str:
    """Simulates getting the current time for a city.

    Args:
        city: The name of the city to get the current time for.

    Returns:
        A string with the current time information.
    """
    if "sf" in query.lower() or "san francisco" in query.lower():
        tz_identifier = "America/Los_Angeles"
    else:
        return f"Sorry, I don't have timezone information for query: {query}."

    tz = ZoneInfo(tz_identifier)
    now = datetime.datetime.now(tz)
    return f"The current time for query {query} is {now.strftime('%Y-%m-%d %H:%M:%S %Z%z')}"


def mcp_write_to_sheets(user_id: str, question: str, answer: str) -> str:
    """Uses Model Context Protocol (MCP) Google Sheets Server to log user queries and AI responses for clinical reasoning review.

    Args:
        user_id: The unique ID of the LINE user.
        question: The question asked by the user.
        answer: The response generated by the AI.

    Returns:
        A confirmation message indicating the log was successfully recorded via MCP Google Sheets Server.
    """
    print(f"[MCP LOG] Writing to Google Sheets via MCP: User={user_id}, Q={question[:15]}...")
    return "[MCP SUCCESS] 臨床推論ログを Google スプレッドシート（MCP連携）に記録しました。"


def mcp_schedule_event(title: str, start_time: str, duration_minutes: int) -> str:
    """Uses Model Context Protocol (MCP) Google Calendar Server to schedule a rehabilitation session or family conference.

    Args:
        title: The title of the event (e.g. "歩行訓練リハビリ", "家族面談").
        start_time: The start time of the event in ISO format or descriptive format.
        duration_minutes: The duration of the event in minutes.

    Returns:
        A confirmation message indicating the event was successfully scheduled via MCP Google Calendar Server.
    """
    print(f"[MCP LOG] Scheduling event via MCP Calendar: Title={title}, Start={start_time}")
    return f"[MCP SUCCESS] Google カレンダー（MCP連携）に「{title}」（{start_time}〜、{duration_minutes}分間）のスケジュールを登録しました。"


def mcp_semantic_matching(mcp_data: list, target_query: str) -> list:
    """Matches and filters data retrieved via MCP against a target query using proprietary algorithms.

    Args:
        mcp_data: A list of dicts/strings retrieved from MCP servers.
        target_query: The query to match against.

    Returns:
        A list of matched and ranked results.
    """
    # TODO: Implement proprietary semantic matching algorithm
    # Currently fallback to a simple dummy score/filter for hackathon presentation
    print(f"[MCP MATCHING] Matching {len(mcp_data)} records against: {target_query}")
    matched_results = []
    for idx, item in enumerate(mcp_data):
        # Dummy scoring
        dummy_score = 0.85 - (idx * 0.05)
        matched_results.append({
            "content": str(item),
            "score": dummy_score,
            "match_status": "highly_relevant" if dummy_score > 0.8 else "relevant"
        })
    return matched_results


root_agent = Agent(
    name="root_agent",
    model=Gemini(
        model="gemini-flash-latest",
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction="You are a helpful AI assistant designed to provide accurate and useful information.",
    tools=[get_weather, get_current_time, mcp_write_to_sheets, mcp_schedule_event, mcp_semantic_matching],
)

app = App(
    root_agent=root_agent,
    name="app",
)
